lexik_jwt_authentication:
    user_identity_field: email
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 300 # 5min

when@dev:
    lexik_jwt_authentication:
        token_ttl: 43200 # 12h